services:
  api:
    container_name: private_share
    image: sagar1343/private_share:1.0.2
    environment:
      - DJANGO_SETTINGS_MODULE=private_share.settings.production
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./static:/staticfiles
    depends_on:
      - redis
      - celery
      - celery_beat
    command: >
      sh -c "python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 private_share.wsgi:application"

  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - redis_data:/data

  celery:
    container_name: celery
    image: sagar1343/private_share:1.0.2
    environment:
      - DJANGO_SETTINGS_MODULE=private_share.settings.production
    env_file:
      - .env
    command: ["celery", "-A", "private_share", "worker", "-l", "INFO"]
    depends_on:
      - redis

  celery_beat:
    container_name: celery_beat
    image: sagar1343/private_share:1.0.2
    environment:
      - DJANGO_SETTINGS_MODULE=private_share.settings.production
    env_file:
      - .env
    command: ["celery", "-A", "private_share", "beat", "-l", "INFO"]
    depends_on:
      - redis

  flower:
    image: sagar1343/private_share:1.0.2
    container_name: flower
    environment:
      - DJANGO_SETTINGS_MODULE=private_share.settings.production
    env_file:
      - .env
    ports:
      - "5555:5555"
    command: ["celery", "-A", "private_share", "flower"]
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static:/staticfiles
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email sagarchakrawarti25@gmail.com -d api.private-share.sagarcodes.me --agree-tos

volumes:
  redis_data:
