services:
  api:
    image: sagar1343/private_share:1.1.0
    environment:
      - DJANGO_SETTINGS_MODULE=private_share.settings.production
    env_file:
      - .env
    expose:
      - "8000"
    volumes:
      - ./static:/staticfiles
    depends_on:
      - redis
      - celery
      - celery_beat
    command: >
      sh -c "python manage.py collectstatic --noinput && uvicorn private_share.asgi:application --host 0.0.0.0 --port 8000"
    restart: on-failure

  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - redis_data:/data
    restart: on-failure

  celery:
    container_name: celery
    image: sagar1343/private_share:1.1.0
    environment:
      - DJANGO_SETTINGS_MODULE=private_share.settings.production
    env_file:
      - .env
    command: ["celery", "-A", "private_share", "worker", "-l", "INFO"]
    depends_on:
      - redis
    restart: on-failure

  celery_beat:
    container_name: celery_beat
    image: sagar1343/private_share:1.1.0
    environment:
      - DJANGO_SETTINGS_MODULE=private_share.settings.production
    env_file:
      - .env
    command: ["celery", "-A", "private_share", "beat", "-l", "INFO"]
    depends_on:
      - redis
    restart: on-failure

  flower:
    image: sagar1343/private_share:1.1.0
    container_name: flower
    environment:
      - DJANGO_SETTINGS_MODULE=private_share.settings.production
    env_file:
      - .env
    ports:
      - "5555:5555"
    command: ["celery", "-A", "private_share", "flower"]
    depends_on:
      - redis
    restart: on-failure

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static:/staticfiles
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api
    restart: on-failure

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email sagarchakrawarti25@gmail.com -d api.private-share.sagarcodes.me --agree-tos
    restart: on-failure

volumes:
  redis_data:
