# Generated by Django 5.2b1 on 2025-03-02 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessLogs',
            new_name='AccessLog',
        ),
        migrations.RenameField(
            model_name='privatefile',
            old_name='collection',
            new_name='collections',
        ),
        migrations.CreateModel(
            name='FilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaders', models.ManyToManyField(blank=True, related_name='downloadable_files', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.privatefile')),
                ('viewers', models.ManyToManyField(blank=True, related_name='viewable_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Recipient',
        ),
    ]
