# Generated by Django 5.1.7 on 2025-03-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_rename_accesslogs_accesslog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepermission',
            name='viewers',
        ),
        migrations.AddField(
            model_name='privatefile',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
