# Generated by Django 5.1.7 on 2025-03-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_remove_filepermission_viewers_privatefile_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filepermission',
            old_name='downloaders',
            new_name='allowed_users',
        ),
    ]
