# Generated by Django 5.1.7 on 2025-03-13 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_rename_downloaders_filepermission_allowed_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepermission',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filepermission',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_permissions', to='vault.privatefile'),
        ),
        migrations.AlterField(
            model_name='privatefile',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
