# Generated by Django 5.1.7 on 2025-03-28 15:08

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_alter_filepermission_allowed_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatefile',
            name='max_download_count',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('user', 'title')},
        ),
    ]
