# Generated by Django 5.1.7 on 2025-03-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_alter_collection_unique_together_fileshare'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileShare',
        ),
    ]
