# Generated by Django 5.1.8 on 2025-05-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0010_alter_accesslog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepermission',
            name='allowed_users',
        ),
        migrations.AddField(
            model_name='filepermission',
            name='allowed_users',
            field=models.JSONField(default=list),
        ),
    ]
