# Generated by Django 5.1.8 on 2025-05-26 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0011_remove_filepermission_allowed_users_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatefile',
            options={'ordering': ['-created_at']},
        ),
    ]
