# Generated by Django 5.2.1 on 2025-05-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0012_alter_privatefile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatefile',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
